info:
  namespace: "lootcrat_plus"
        
items:
 ##################normal##########################
  ##################box##################
  amethyst_box:
    display_name: "Amethyst box common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/amethyst_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  diamond_box:
    display_name: "Diamond box common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/diamond_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  emerald_box:
    display_name: "Emerald box common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/emerald_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
  gold_box:
    display_name: "Gold box common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/gold_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  iron_box:
    display_name: "Iron box common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/iron_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
 ##################keys##################       
  amethyst_key:
    display_name: "amethyst key common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/amethyst_key
      
  diamond_key:
    display_name: "Diamond key common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/diamond_key
      
  emerald_key:
    display_name: "Emerald key common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/emerald_key
  gold_key:
    display_name: "Gold key common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/gold_key
  iron_key:
    display_name: "Iron key common"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: normal/iron_key
      
 ##################rare##########################
  ##################box##################
  amethyst_box_rare:
    display_name: "Amethyst box &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/amethyst_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  diamond_box_rare:
    display_name: "Diamond box &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/diamond_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  emerald_box_rare:
    display_name: "Emerald box &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/emerald_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
  gold_box_rare:
    display_name: "Gold box &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/gold_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  iron_box_rare:
    display_name: "Iron box &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/iron_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
 ##################keys##################       
  amethyst_key_rare:
    display_name: "amethyst key &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/amethyst_key
      
  diamond_key_rare:
    display_name: "Diamond key &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/diamond_key
      
  emerald_key_rare:
    display_name: "Emerald key &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/emerald_key
  gold_key_rare:
    display_name: "Gold key &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/gold_key
  iron_key_rare:
    display_name: "Iron key &6rare"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: rare/iron_key


 ##################epic##########################
  ##################box##################
  amethyst_box_epic:
    display_name: "Amethyst box &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/amethyst_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  diamond_box_epic:
    display_name: "Diamond box &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/diamond_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  emerald_box_epic:
    display_name: "Emerald box &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/emerald_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
  gold_box_epic:
    display_name: "Gold box &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/gold_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  iron_box_epic:
    display_name: "Iron box &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/iron_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
 ##################keys##################       
  amethyst_key_epic:
    display_name: "amethyst key &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/amethyst_key
      
  diamond_key_epic:
    display_name: "Diamond key &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/diamond_key
      
  emerald_key_epic:
    display_name: "Emerald key &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/emerald_key
  gold_key_epic:
    display_name: "Gold key &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/gold_key
  iron_key_epic:
    display_name: "Iron key &bepic"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: epic/iron_key
      
 ##################legendary##########################
  ##################box##################
  amethyst_box_legendary:
    display_name: "Amethyst box &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/amethyst_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  diamond_box_legendary:
    display_name: "Diamond box &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/diamond_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  emerald_box_legendary:
    display_name: "Emerald box &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/emerald_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
  gold_box_legendary:
    display_name: "Gold box &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/gold_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
       
  iron_box_legendary:
    display_name: "Iron box &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/iron_box
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: true
          walls: true
 ##################keys##################       
  amethyst_key_legendary:
    display_name: "amethyst key &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/amethyst_key
      
  diamond_key_legendary:
    display_name: "Diamond key &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/diamond_key
      
  emerald_key_legendary:
    display_name: "Emerald key &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/emerald_key
  gold_key_legendary:
    display_name: "Gold key &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/gold_key
  iron_key_legendary:
    display_name: "Iron key &5legendary"
    permission: lootcrat.plus
    resource:
      material: PAPER
      generate: false
      model_path: legendary/iron_key