info:
  namespace: lootcrat_plus
categories:
  lootcrat_plus:
    enabled: true
    skip_if_already: false
    icon: "lootcrat_plus:emerald_box_epic"
    name: "&6&lLoot Crate &2&lPlus"
    permission: lootcrat.plus
    items:
     #common
      - "lootcrat_plus:amethyst_box"
      - "lootcrat_plus:amethyst_key"
      - "lootcrat_plus:diamond_box"
      - "lootcrat_plus:diamond_key"
      - "lootcrat_plus:emerald_box"
      - "lootcrat_plus:emerald_key"
      - "lootcrat_plus:gold_box"
      - "lootcrat_plus:gold_key"
      - "lootcrat_plus:iron_box"
      - "lootcrat_plus:iron_key"
      #rare
      - "lootcrat_plus:amethyst_box_rare"
      - "lootcrat_plus:amethyst_key_rare"
      - "lootcrat_plus:diamond_box_rare"
      - "lootcrat_plus:diamond_key_rare"
      - "lootcrat_plus:emerald_box_rare"
      - "lootcrat_plus:emerald_key_rare"
      - "lootcrat_plus:gold_box_rare"
      - "lootcrat_plus:gold_key_rare"
      - "lootcrat_plus:iron_box_rare"
      - "lootcrat_plus:iron_key_rare" 
       #epic
      - "lootcrat_plus:amethyst_box_epic"        
      - "lootcrat_plus:amethyst_key_epic"        
      - "lootcrat_plus:diamond_box_epic"        
      - "lootcrat_plus:diamond_key_epic"        
      - "lootcrat_plus:emerald_box_epic"        
      - "lootcrat_plus:emerald_key_epic"        
      - "lootcrat_plus:emerald_key_epic"        
      - "lootcrat_plus:gold_box_epic"        
      - "lootcrat_plus:gold_key_epic"        
      - "lootcrat_plus:iron_box_epic"        
      - "lootcrat_plus:iron_key_epic"        
       #legendary
      - "lootcrat_plus:amethyst_box_legendary"        
      - "lootcrat_plus:amethyst_key_legendary"        
      - "lootcrat_plus:diamond_box_legendary"        
      - "lootcrat_plus:diamond_key_legendary"        
      - "lootcrat_plus:emerald_box_legendary"        
      - "lootcrat_plus:emerald_key_legendary"        
      - "lootcrat_plus:emerald_key_legendary"        
      - "lootcrat_plus:gold_box_legendary"        
      - "lootcrat_plus:gold_key_legendary"        
      - "lootcrat_plus:iron_box_legendary"        
      - "lootcrat_plus:iron_key_legendary"
# 416232948493481688019110