info:
  namespace: park_plus
categories:
  park_plus:
    enabled: true
    skip_if_already: false
    icon: "park_plus:swing"
    name: Park plus
    permission: ia.menu.buildplus
    items:
      - "park_plus:bench"
      - "park_plus:log_bench"
      - "park_plus:box"
      - "park_plus:little_box"
      - "park_plus:concret_pot_plant"
      - "park_plus:wooden_flower_pot"
      - "park_plus:picnic_table"
      - "park_plus:picnic_table_nappe"
      - "park_plus:bird_house"      
      - "park_plus:stele_1"
      - "park_plus:stele_2"
      - "park_plus:stele_3"
      - "park_plus:stele_4"
      - "park_plus:stele_5"
      - "park_plus:street_lamp"
      - "park_plus:street_lamp_double"
      - "park_plus:street_lamp_quadruple"
      - "park_plus:street_lamp_upper_double"
      - "park_plus:street_lamp_upper"
      - "park_plus:street_lamp_upper_quadruple"
      - "park_plus:street_lamp_upper_triple"
      - "park_plus:lantern_box"      
      - "park_plus:swing"
      - "park_plus:fence"
      - "park_plus:light_wooden_pallet"
      - "park_plus:wooden_pallet"
      - "park_plus:wooden_ground_planks"
      - "park_plus:box_construction"
      - "park_plus:under_construction"      

