info:
  namespace: "park_plus"
        
items:

  bench:
    display_name: "Bench"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: bench
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 2
          height: 1
          width_offset: -0.5
      furniture_sit:
        sit_height: 0.8
        sit_all_solid_blocks: true        
  box:
    display_name: "Wooden box"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: box
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  box_construction:
    display_name: "Construction box"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: box_construction
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  under_construction:
    display_name: "Under construction"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: under_construction
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
          
  little_box:
    display_name: "little box"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: little_box
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
          
  concret_pot_plant:
    display_name: "Concret pot plant"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: concret_pot_plant
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
          
  wooden_flower_pot:
    display_name: "Wooden pot flower"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: wooden_flower_pot
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
  log_bench:
    display_name: "Log bench"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: log_bench
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
      furniture_sit:
        sit_height: 0.9
        
  picnic_table:
    display_name: "Picnic table"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: picnic_table
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1

  picnic_table_nappe:
    display_name: "Picnic table with tablecloth"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: picnic_table_nappe
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1

  stele_1:
    display_name: "Stele 1"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: stele_1
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  stele_2:
    display_name: "Stele 2"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: stele_2
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  stele_3:
    display_name: "Stele 3"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: stele_3
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  stele_4:
    display_name: "Stele 4"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: stele_4
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2
  stele_5:
    display_name: "Stele 5"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: stele_5
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  street_lamp:
    display_name: "Street lamp "
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2
          
  street_lamp_double:
    display_name: "Street lamp double"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp_double
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  street_lamp_quadruple:
    display_name: "Street lamp quadruple"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp_quadruple
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  street_lamp_upper:
    display_name: "Street lamp upper"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp_upper
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2
  street_lamp_upper_double:
    display_name: "Street lamp upper double"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp_upper_double
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  street_lamp_upper_quadruple:
    display_name: "Street lamp upper quadruple"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp_upper_quadruple
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  street_lamp_upper_triple:
    display_name: "Street lamp upper triple"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: street_lamp_upper_triple
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2

  swing:
    display_name: "Swing"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: swing
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: false       
        placeable_on:
          floor: true
          ceiling: false
          walls: false


  bird_house:
    display_name: "Bird house"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: bird_house
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: false       
        placeable_on:
          floor: true
          ceiling: true
          walls: true


  fence:
    display_name: "Wooden Fence"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: fence
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: false       
        placeable_on:
          floor: true
          ceiling: true
          walls: true


  light_wooden_pallet:
    display_name: "Light wooden pallet"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: light_wooden_pallet
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: false       
        placeable_on:
          floor: true
          ceiling: true
          walls: true

  wooden_pallet:
    display_name: "Wooden pallet"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: wooden_pallet
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: false       
        placeable_on:
          floor: true
          ceiling: true
          walls: true

  wooden_ground_planks:
    display_name: "Wooden ground planks"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: wooden_ground_planks
    behaviours:
      furniture:
        fixed_rotation: true
        small: false
        solid: false       
        placeable_on:
          floor: true
          ceiling: true
          walls: true

  lantern_box:
    display_name: "Lantern box"
    permission: itemsadder.park_plus
    resource:
      material: PAPER
      generate: false
      model_path: lantern_box
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        light_level: 17        
        placeable_on:
          floor: true
          ceiling: true
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1

        

# 6927ZQMG9H