info:
  namespace: gexary
recipes:
  crafting_table:
    elevator:
      permission: gexary.elevator
      enabled: true
      pattern:
      - ABA
      - BAB
      - ABA
      ingredients:
        A: DEEPSLATE_BRICKS
        B: ENDER_PEARL
      result:
        item: gexary:elevator
        amount: 1
items:
  elevator:
    display_name: ยง3Elevator
    permission: elevator
    resource:
      generate: true
      material: PAPER
      textures:
        - block/elevator.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        light_level: 7
        break_tools_whitelist:
          - PICKAXE
        hardness: 3
        sound:
          break:
            name: minecraft:block.metal.break
          place:
            name: minecraft:block.metal.place
          hit:
            name: minecraft:block.metal.hit
          step:
            name: minecraft:block.metal.step
          fall:
            name: minecraft:block.metal.fall