info:
  namespace: furnituresplus
categories:
  furnituresplus:
    enabled: true
    skip_if_already: false
    icon: "furnituresplus:cyan_bedside_table"
    name: Furnitures plus
    permission: ia.menu.furnituresplus
    items:
      - "furnituresplus:fabric_machine_plus"
      - "furnituresplus:red_wooden_sofa_left"
      - "furnituresplus:red_wooden_sofa_middle"
      - "furnituresplus:red_wooden_sofa_right"
      - "furnituresplus:red_wooden_sofa_corner"
      - "furnituresplus:red_wooden_sofa_single" 
      - "furnituresplus:red_lowtable" 
      - "furnituresplus:red_wooden_buffettable" 
      - "furnituresplus:red_bedside_table" 
      - "furnituresplus:red_wooden_biglamp" 
      - "furnituresplus:red_wooden_lamp" 
      - "furnituresplus:red_wooden_hanginglamp" 
      - "furnituresplus:red_oakpaint" 
      - "furnituresplus:red_wooden_chair" 
      - "furnituresplus:red_wooden_diningtable" 
      - "furnituresplus:red_storage_furniture" 
     #######
      - "furnituresplus:white_wooden_sofa_left"
      - "furnituresplus:white_wooden_sofa_middle"
      - "furnituresplus:white_wooden_sofa_right"
      - "furnituresplus:white_wooden_sofa_corner"
      - "furnituresplus:white_wooden_sofa_single"  
      - "furnituresplus:white_wooden_lowtable"  
      - "furnituresplus:white_wooden_buffettable"  
      - "furnituresplus:white_bedside_table"  
      - "furnituresplus:white_wooden_biglamp"  
      - "furnituresplus:white_wooden_lamp"  
      - "furnituresplus:white_wooden_hanginglamp"  
      - "furnituresplus:white_sprucepaint"  
      - "furnituresplus:white_wooden_chair"  
      - "furnituresplus:white_wooden_diningtable"  
      - "furnituresplus:white_storage_furniture"  
     #######      
      - "furnituresplus:cyan_wooden_sofa_left"      
      - "furnituresplus:cyan_wooden_sofa_middle"      
      - "furnituresplus:cyan_wooden_sofa_right"      
      - "furnituresplus:cyan_wooden_sofa_corner" 
      - "furnituresplus:cyan_wooden_sofa_single"        
      - "furnituresplus:cyan_lowtable"        
      - "furnituresplus:cyan_buffet_table"        
      - "furnituresplus:cyan_bedside_table"        
      - "furnituresplus:cyan_wooden_biglamp"        
      - "furnituresplus:cyan_wooden_lamp"        
      - "furnituresplus:cyan_wooden_hanginglamp"        
      - "furnituresplus:cyan_summerpaint"        
      - "furnituresplus:cyan_wooden_chair"        
      - "furnituresplus:cyan_wooden_diningtable"        
      - "furnituresplus:cyan_storage_furniture"    
     #######      
      - "furnituresplus:gray_wooden_sofa_left"      
      - "furnituresplus:gray_wooden_sofa_middle"      
      - "furnituresplus:gray_wooden_sofa_right"      
      - "furnituresplus:gray_wooden_sofa_corner"             
      - "furnituresplus:gray_wooden_sofa_single" 
      - "furnituresplus:gray_wooden_lowtable" 
      - "furnituresplus:gray_wooden_buffettable" 
      - "furnituresplus:gray_bedside_table" 
      - "furnituresplus:gray_wooden_biglamp" 
      - "furnituresplus:gray_wooden_lamp" 
      - "furnituresplus:gray_wooden_hanginglamp" 
      - "furnituresplus:gray_acaciapaint" 
      - "furnituresplus:gray_wooden_chair" 
      - "furnituresplus:gray_wooden_diningtable" 
      - "furnituresplus:gray_storage_furniture" 
     #######      
      - "furnituresplus:iron_sofa_left"      
      - "furnituresplus:iron_sofa_middle"      
      - "furnituresplus:iron_sofa_right"      
      - "furnituresplus:iron_sofa_corner"             
      - "furnituresplus:iron_sofa_single" 
      - "furnituresplus:iron_lowtable" 
      - "furnituresplus:iron_buffettable" 
      - "furnituresplus:iron_bedside_table" 
      - "furnituresplus:iron_biglamp" 
      - "furnituresplus:iron_lamp" 
      - "furnituresplus:iron_hanginglamp" 
      - "furnituresplus:iron_paint" 
      - "furnituresplus:iron_chair" 
      - "furnituresplus:iron_diningtable" 
      - "furnituresplus:iron_storage_furniture" 
     #######
      - "furnituresplus:amethyst_sofa_left" 
      - "furnituresplus:amethyst_sofa_middle" 
      - "furnituresplus:amethyst_sofa_right" 
      - "furnituresplus:amethyst_sofa_corner" 
      - "furnituresplus:amethyst_sofa_single" 
      - "furnituresplus:amethyst_lowtable" 
      - "furnituresplus:amethys_buffet_table" 
      - "furnituresplus:amethyst_bedside_table" 
      - "furnituresplus:amethyst_biglamp" 
      - "furnituresplus:amethyst_lamp" 
      - "furnituresplus:amethyst_hanginglamp" 
      - "furnituresplus:amethyst_paint" 
      - "furnituresplus:amethyst_chair" 
      - "furnituresplus:amethyst_diningtable" 
      - "furnituresplus:amethyst_storage_furniture" 
     #######
      - "furnituresplus:radio" 
      - "furnituresplus:bluepaint" 
      - "furnituresplus:greenpaint" 
      - "furnituresplus:greenpaintb" 
      
 
 

# 33291CH3ZPAOKYW9LC