info:
  namespace: elitecreatures
categories:
  modern_furniture_pack_vol2:
    enabled: true
    icon: "elitecreatures:modern_furniture_pack_vol2_shelf"
    name: "Modern Furniture Pack v2"
    permission: "ia.menu.modern_furniture_pack_vol2"
    items:
      - "elitecreatures:modern_furniture_pack_vol2_bed"
      - "elitecreatures:modern_furniture_pack_vol2_board"
      - "elitecreatures:modern_furniture_pack_vol2_cabinet"
      - "elitecreatures:modern_furniture_pack_vol2_carpet"
      - "elitecreatures:modern_furniture_pack_vol2_chair"
      - "elitecreatures:modern_furniture_pack_vol2_computerchair"
      - "elitecreatures:modern_furniture_pack_vol2_computerdesk"
      - "elitecreatures:modern_furniture_pack_vol2_lamp"
      - "elitecreatures:modern_furniture_pack_vol2_macbook"
      - "elitecreatures:modern_furniture_pack_vol2_picture"
      - "elitecreatures:modern_furniture_pack_vol2_plantpot"
      - "elitecreatures:modern_furniture_pack_vol2_shelf"
      - "elitecreatures:modern_furniture_pack_vol2_sofa_01"
      - "elitecreatures:modern_furniture_pack_vol2_sofa_02"
      - "elitecreatures:modern_furniture_pack_vol2_table_01"
      - "elitecreatures:modern_furniture_pack_vol2_table_02"
      - "elitecreatures:modern_furniture_pack_vol2_table_03"
      - "elitecreatures:modern_furniture_pack_vol2_tv"
      - "elitecreatures:modern_furniture_pack_vol2_wardrobe_01"
      - "elitecreatures:modern_furniture_pack_vol2_wardrobe_02"


# 53881026RT9HLWYGR7RI4