info:
  namespace: elitecreatures
items:
  modern_furniture_pack_vol2_bed:
    display_name: Bed
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/bed
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 3
          width: 2
          height: 1
          length_offset: -1
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_board:
    display_name: Board
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/board
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  modern_furniture_pack_vol2_cabinet:
    display_name: Cabinet
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/cabinet
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: -1
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_carpet:
    display_name: Carpet
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/carpet
    behaviours:
      furniture:
        solid: false
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 3
          width: 3
          height: 1
          length_offset: 0.5
          width_offset: 0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_chair:
    display_name: Chair
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/chair
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.95
        opposite_direction: false
        sit_all_solid_blocks: true
  modern_furniture_pack_vol2_computerchair:
    display_name: Computer Chair
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/computerchair
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.95
        opposite_direction: false 
        sit_all_solid_blocks: true
  modern_furniture_pack_vol2_computerdesk:
    display_name: Computer Desk
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/computerdesk
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_lamp:
    display_name: Lamp
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/lamp
    behaviours:
      furniture:
        solid: true
        light_level: 10
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_macbook:
    display_name: MacBook
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/macbook
    behaviours:
      furniture:
        solid: true
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_picture:
    display_name: Picture
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/picture
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 2
          length_offset: 0
          width_offset: 0.5
          height_offset: 0.5
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  modern_furniture_pack_vol2_plantpot:
    display_name: Plant Pot
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/plantpot
    behaviours:
      furniture:
        solid: true
        fixed_rotation: false
        entity: item_frame
        hitbox: 
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_shelf:
    display_name: Shelf
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/shelf
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
            walls: false
            ceiling: false
            floor: true
  modern_furniture_pack_vol2_sofa_01:
    display_name: Sofa 1
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/sofa_01
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.85
        opposite_direction: true 
        sit_all_solid_blocks: true
  modern_furniture_pack_vol2_sofa_02:
    display_name: Sofa 2
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/sofa_02
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.85
        opposite_direction: true 
        sit_all_solid_blocks: true
  modern_furniture_pack_vol2_table_01:
    display_name: Table 1
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/table_01
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_table_02:
    display_name: Table 2
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/table_02
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_table_03:
    display_name: Table 3
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/table_03
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 2
          width: 2
          height: 1
          length_offset: -0.5
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_tv:
    display_name: TV
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/tv
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_wardrobe_01:
    display_name: Wardrobe 1
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/wardrobe_01
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 2
          length_offset: 0
          width_offset: -0.5
          height_offset: -0.5
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  modern_furniture_pack_vol2_wardrobe_02:
    display_name: Wardrobe 2
    resource:
      material: paper
      generate: false
      model_path: modern_furniture_pack_vol2/wardrobe_02
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true