info:
  namespace: omc_icons
font_images:
  openmc-armor-icon:
    permission: openmc-armor-icon
    show_in_gui: false
    path: "openmc-armor-icon.png"
    scale_ratio: 12
    y_position: 10
  server-icon:
    permission: server-icon
    show_in_gui: false
    path: "server-icon.png"
    scale_ratio: 12
    y_position: 10   