info:
  namespace: space
items:
  cheese:
    display_name: "Fromage"
    lore:
      - ""
      - "§r§fFromton."
      - ""
    resource:
      generate: true
      material: COOKED_BEEF
      textures:
        - "cheese"
    events:
      eat:
        feed:
          amount: 4
          saturation: 1.5
recipes:
  crafting_table:
    cheese:
      enabled: true
      pattern:
        - SS
        - SS
      ingredients:
        S: "space:moon_shard"
      result:
        item: "space:cheese"
        amount: 1