info:
  namespace: space
items:
  launchbtn:
    enabled: true
    display_name: "§r"
    resource:
      material: PAPER
      model_path: "launchbtn"
  launchbtndisabled:
    enabled: true
    display_name: "§r"
    resource:
      material: PAPER
      model_path: "launchbtndisabled"
  invisiblebtn:
    enabled: true
    display_name: "§r"
    resource:
      material: PAPER
      generate: true
      textures:
        - "invisible.png"