info:
  namespace: space
items:
  moon_shard:
    display_name: "Éclat de lune"
    lore:
      - ""
      - "§r§fUn simple fragment de roche lunaire."
      - ""
    resource:
      generate: true
      material: PAPER
      textures:
        - "moon_shard"