info:
  namespace: space
items:
  moon_milk_bucket:
    display_name: "Seau de lait lunaire"
    lore:
      - ""
      - "§r§fObtenu lors de la traite d'une vache lunaire."
      - ""
    resource:
      generate: true
      material: MILK_BUCKET
      textures:
        - "moon_milk_bucket"