info:
  namespace: space
items:
  moon_sword:
    display_name: "Épée Lunaire"
    lore:
      - ""
      - "§r§fCette épée est vraiment lunaire."
      - "§r§f§oPermet d'envoyer ses ennemis dans l'espace."
      - ""
    resource:
      material: GOLDEN_SWORD
      generate: true
      textures:
        - moon_sword.png