info:
  namespace: space
entities:
  rocket:
    display_name: "Fusée"
    type: ARMOR_STAND
    model_folder: entity/rocket
    silent: true
    ai: false
    shadow: false
    speed:
      movement: 1
      flying: 0
    max_health: 20
items:
  rocket:
    display_name: "Fusée"
    permission: rocket
    resource:
      material: LEATHER_HORSE_ARMOR
      generate: true
      textures:
        - "rocket_item"
    item_flags:
      - HIDE_ATTRIBUTES
recipes:
  crafting_table:
    rocket:
      enabled: true
      pattern:
        - XSX
        - CIC
        - CXC
      ingredients:
        C: "COPPER_INGOT"
        S: "space:moon_shard"
        I: "space:steel_block"
      result:
        item: "space:rocket"
        amount: 1