info:
  namespace: space
items:
  steel_ingot:
    display_name: "Lingot d'acier"
    lore:
      - ""
      - "§r§fOn en a jamais acier."
      - ""
    resource:
      generate: true
      material: PAPER
      textures:
        - "steel_ingot"
  steel_block:
    display_name: "Bloc d'acier"
    lore:
      - ""
      - "§r§f Je pense que c'est acier."
      - ""
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
      hardness: 5
      blast_resistance: 5
    resource:
      generate: true
      material: PAPER
      textures:
        - "steel_block"
recipes:
  cooking:
    steel_ingot:
      exp: 10
      cook_time: 1800
      machines:
        - FURNACE
        - BLAST_FURNACE
      ingredient:
        item: IRON_INGOT
      result:
        item: "space:steel_ingot"
        amount: 1
  crafting_table:
    steel_block:
      enabled: true
      pattern:
        - SSS
        - SSS
        - SSS
      ingredients:
        S: "space:steel_ingot"
      result:
        item: "space:steel_block"
        amount: 1