info:
  namespace: luckyblock
items:
  luckyblock:
    display_name: §dLucky Block
    permission: luckyblock
    lore:
      - "§7Déclenche un event aléatoire lorsqu'il est cassé."
      - "§cAttention, certains events peuvent causer une altération"
      - "§cdu terrain, ne pas ouvrir à côté de votre base !"
      - "§cPrivilégiez une zone plate."
      - ""
      - "§6Sneak + Clique droit sur le block posé -> voir les events"
    resource:
      generate: true
      material: PAPER
      textures:
        - blocks/luckyblock.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: true
        sound:
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 1
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 1