info:
  namespace: elitecreatures
categories:
  hotel_furniture_v1:
    enabled: true
    icon: "elitecreatures:hotel_furniture_v1_bed"
    name: 'Hotel Furniture v1'
    permission: "ia.menu.hotelfurniture_v1"
    items:
      - "elitecreatures:hotel_furniture_v1_air_conditioner"
      - "elitecreatures:hotel_furniture_v1_bed"
      - "elitecreatures:hotel_furniture_v1_chair_single"
      - "elitecreatures:hotel_furniture_v1_cupboard"
      - "elitecreatures:hotel_furniture_v1_footstool"
      - "elitecreatures:hotel_furniture_v1_lamp"
      - "elitecreatures:hotel_furniture_v1_lamp_high"
      - "elitecreatures:hotel_furniture_v1_lamp_wall"
      - "elitecreatures:hotel_furniture_v1_painting"
      - "elitecreatures:hotel_furniture_v1_phone"
      - "elitecreatures:hotel_furniture_v1_shelf"
      - "elitecreatures:hotel_furniture_v1_sofa_red"
      - "elitecreatures:hotel_furniture_v1_sofa_red_corner"
      - "elitecreatures:hotel_furniture_v1_table"
      - "elitecreatures:hotel_furniture_v1_table_long"
      - "elitecreatures:hotel_furniture_v1_table_long_2"
      - "elitecreatures:hotel_furniture_v1_table_with_drawer"
      - "elitecreatures:hotel_furniture_v1_table_with_self"
      - "elitecreatures:hotel_furniture_v1_tree"
      - "elitecreatures:hotel_furniture_v1_tv"

