info:
  namespace: elitecreatures
items:
  hotel_furniture_v1_air_conditioner:
    display_name: Air Conditioner
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/air_conditioner
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  hotel_furniture_v1_bed:
    display_name: Bed
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/bed
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 3
          width: 3
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
      furniture_sit:
        sit_height: 1.3
        opposite_direction: true
        sit_all_solid_blocks: true
  hotel_furniture_v1_chair_single:
    display_name: Chair Single
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/chair_single
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
      furniture_sit:
        sit_height: 0.8
        opposite_direction: true
        sit_all_solid_blocks: true
  hotel_furniture_v1_cupboard:
    display_name: Cupboard
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/cupboard
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
  hotel_furniture_v1_footstool:
    display_name: Footstool
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/footstool
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
      furniture_sit:
        sit_height: 0.5
        opposite_direction: true
        sit_all_solid_blocks: true
  hotel_furniture_v1_lamp:
    display_name: Lamp
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/lamp
    behaviours:
      furniture:
        light_level: 14
        solid: false
        fixed_rotation: falses
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  hotel_furniture_v1_lamp_high:
    display_name: Lamp High
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/lamp_high
    behaviours:
      furniture:
        light_level: 14
        solid: false
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  hotel_furniture_v1_lamp_wall:
    display_name: Lamp Wall
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/lamp_wall
    behaviours:
      furniture:
        light_level: 14
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  hotel_furniture_v1_painting:
    display_name: Painting
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/painting
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  hotel_furniture_v1_phone:
    display_name: Phone
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/phone
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  hotel_furniture_v1_shelf:
    display_name: Shelf
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/shelf
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 3
          length_offset: 0
          width_offset: 0
          height_offset: 0
  hotel_furniture_v1_sofa_red:
    display_name: Sofa Red
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/sofa_red
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
      furniture_sit:
        sit_height: 0.8
        opposite_direction: true
        sit_all_solid_blocks: true
  hotel_furniture_v1_sofa_red_corner:
    display_name: Sofa Red Corner
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/sofa_red_corner
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
      furniture_sit:
        sit_height: 0.8
        opposite_direction: true
        sit_all_solid_blocks: true
  hotel_furniture_v1_table:
    display_name: Table
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/table
    behaviours:
      furniture:
        solid: true
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  hotel_furniture_v1_table_long:
    display_name: Table Long
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/table_long
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
  hotel_furniture_v1_table_long_2:
    display_name: Table Long 2
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/table_long_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
  hotel_furniture_v1_table_with_drawer:
    display_name: Table With Drawer
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/table_with_drawer
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
  hotel_furniture_v1_table_with_self:
    display_name: Table With Self
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/table_with_self
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
  hotel_furniture_v1_tree:
    display_name: Tree
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/tree
    behaviours:
      furniture:
        solid: false
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  hotel_furniture_v1_tv:
    display_name: Tv
    resource:
      material: PAPER
      generate: false
      model_path: hotel_furniture_v1/tv
    behaviours:
      furniture:
        solid: false
        fixed_rotation: false
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true

# 37776IOV7C