info:
  namespace: wand
categories:
  wand:
    enabled: true
    skip_if_already: false
    icon: rtpwand
    name: wand
    permission: ia.menu.seecategory.wand
    items:
      - wand:rtpwand
      - wand:claimwand