info:
  namespace: wand
items:
  rtpwand:
    enabled: true
    display_name: RTP Wand
    resource:
      material: WARPED_FUNGUS_ON_A_STICK
      generate: false
      model_path: rtpwand
    durability:
      max_custom_durability: 5
    blocked_enchants:
      - ALL
recipes:
  crafting_table:
    rtpwand:
      enabled: true
      pattern:
      - EXX
      - SXX
      - SXX
      pattern_2:
      - XEX
      - XSX
      - XSX
      pattern_3:
      - XXE
      - XXS
      - XXS
      ingredients:
        E: ENDER_PEARL
        S: STICK
      result:
        item: wand:rtpwand
        amount: 1