info:
  namespace: customitems
items:
  builder_wand:
    permission: customitems.builder_wand
    display_name: Builder Wand
    lore:
    - "ยง7Permet de poser une large zone de blocs"
    resource:
      material: WOODEN_AXE
      generate: false
      model_path: item/builder_wand
    blocked_enchants:
    - ALL
    durability:
      max_custom_durability: 1024
    attribute_modifiers:
      mainhand:
        attackDamage: 1
        attackSpeed: 1