info:
  namespace: customitems
items:
  iron_hammer:
    permission: customitems.iron_hammer
    display_name: <gradient:#ffffff:#ffd08a>Marteau en fer
    lore:
    - "ยง7Permet de creuser une zone de 3x3 blocs"
    resource:
      material: IRON_PICKAXE
      generate: false
      model_path: item/iron_hammer
    blocked_enchants:
      - FORTUNE
      - SILK_TOUCH
    durability:
      max_custom_durability: 512
      
  diamond_hammer:
    permission: customitems.diamond_hammer
    display_name: <gradient:#ffffff:#72f6ef>Marteau en diamant
    lore:
    - "ยง7Permet de creuser une zone de 3x3x3 blocs"
    resource:
      material: DIAMOND_PICKAXE
      generate: false
      model_path: item/diamond_hammer
    blocked_enchants:
      - FORTUNE
      - SILK_TOUCH
    durability:
      max_custom_durability: 2048
      
  netherite_hammer:
    permission: customitems.netherite_hammer
    display_name: <gradient:#ffffff:#6b604f>Marteau en netherite
    lore:
    - "ยง7Permet de creuser une zone de 3x3x3 blocs"
    resource:
      material: NETHERITE_PICKAXE
      generate: false
      model_path: item/netherite_hammer
    blocked_enchants:
      - FORTUNE
      - SILK_TOUCH
    durability:
      max_custom_durability: 4096
  
