info:
  namespace: customitems
recipes:
  crafting_table:
    iron_hammer:
      permission: customitems.iron_hammer
      enabled: true
      pattern:
      - BBB
      - BSB
      - XSX
      ingredients:
        B: IRON_BLOCK
        S: STICK
      result:
        item: customitems:iron_hammer
        amount: 1
        
    diamond_hammer:
      permission: customitems.diamond_hammer
      enabled: true
      pattern:
      - BBB
      - BSB
      - XSX
      ingredients:
        B: DIAMOND_BLOCK
        S: STICK
      result:
        item: customitems:diamond_hammer
        amount: 1
        
    netherite_hammer:
      permission: customitems.netherite_hammer
      enabled: true
      pattern:
      - BBB
      - BSB
      - XSX
      ingredients:
        B: NETHERITE_BLOCK
        S: STICK
      result:
        item: customitems:netherite_hammer
        amount: 1
        
    builder_wand:
      permission: customitems.builder_wand
      enabled: true
      pattern:
      - EDE
      - EBE
      - XBX
      ingredients:
        B: BLAZE_ROD
        D: DIAMOND_BLOCK
        E: EMERALD_BLOCK
      result:
        item: customitems:builder_wand
        amount: 1