info:
  namespace: omc_armors
categories:
  omc_armors:
    enabled: true
    skip_if_already: false
    icon: omc_icons:openmc-armor-icon
    name: "OpenMC Armors"
    permission: ia.menu.seecategory.omc_armors
    items: {}