info:
  namespace: "aywenevent"
font_images:
  text_aywen:
    permission: op
    show_in_gui: false
    path: "font/emoji/text_aywen.png"
    scale_ratio: 40
    y_position: 27
  openmc:
    permission: op
    show_in_gui: false
    path: "font/emoji/openmc.png"
    scale_ratio: 60
    y_position: 57
  fuzeshop:
    permission: op
    show_in_gui: false
    path: "font/emoji/fuzeshop.png"
    scale_ratio: 40
    y_position: 27
  darkdandan:
    permission: op
    show_in_gui: false
    path: "font/emoji/darkdandan.png"
    scale_ratio: 40
    y_position: 40
  lamotte:
    permission: op
    show_in_gui: false
    path: "font/emoji/lamotte.png"
    scale_ratio: 40
    y_position: 40
  aywencheh:
    permission: op
    show_in_gui: false
    path: "font/emoji/aywencheh.png"
    scale_ratio: 40
    y_position: 40