info:
  namespace: elitecreatures
categories:
  office_furniture_v2:
    enabled: true
    icon: "elitecreatures:office_furniture_v2_board_1"
    name: "Office Furniture v2"
    permission: "ia.menu.office_furniture_v2"
    items:
      - "elitecreatures:office_furniture_v2_board_1"
      - "elitecreatures:office_furniture_v2_board_2"
      - "elitecreatures:office_furniture_v2_chairceo"
      - "elitecreatures:office_furniture_v2_chair"
      - "elitecreatures:office_furniture_v2_computer"
      - "elitecreatures:office_furniture_v2_cupboard_1"
      - "elitecreatures:office_furniture_v2_cupboard_2"
      - "elitecreatures:office_furniture_v2_cupboard_3"
      - "elitecreatures:office_furniture_v2_drawer"
      - "elitecreatures:office_furniture_v2_file"
      - "elitecreatures:office_furniture_v2_lamp"
      - "elitecreatures:office_furniture_v2_pottedplants"
      - "elitecreatures:office_furniture_v2_printer"
      - "elitecreatures:office_furniture_v2_projector_1"
      - "elitecreatures:office_furniture_v2_projector_2"
      - "elitecreatures:office_furniture_v2_rubbishbin"
      - "elitecreatures:office_furniture_v2_sofa_1"
      - "elitecreatures:office_furniture_v2_sofa_2"
      - "elitecreatures:office_furniture_v2_tableceo"
      - "elitecreatures:office_furniture_v2_table_1"
      - "elitecreatures:office_furniture_v2_table_2"

# 3922FEQ27AWJYO1Q7PZPX8EBMP