info:
  namespace: elitecreatures
items:
  office_furniture_v2_board_1:
    display_name: Board 1
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/board_1
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  office_furniture_v2_board_2:
    display_name: Board 2
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/board_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 3
          height: 3
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_chairceo:
    display_name: Chairceo
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/chairceo
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.9
        opposite_direction: true
        sit_all_solid_blocks: true
  office_furniture_v2_chair:
    display_name: Chair
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/chair
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.9
        opposite_direction: true
        sit_all_solid_blocks: true
  office_furniture_v2_computer:
    display_name: Computer
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/computer
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_cupboard_1:
    display_name: Cupboard 1
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/cupboard_1
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_cupboard_2:
    display_name: Cupboard 2
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/cupboard_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 2
          height: 2
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_cupboard_3:
    display_name: Cupboard 3
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/cupboard_3
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 2
          height: 3
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_drawer:
    display_name: Drawer
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/drawer
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 2
          height: 2
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_file:
    display_name: File
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/file
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_lamp:
    display_name: Lamp
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/lamp
    behaviours:
      furniture:
        solid: true
        light_level: 14
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_pottedplants:
    display_name: Pottedplants
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/pottedplants
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_printer:
    display_name: Printer
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/printer
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_projector_1:
    display_name: Projector 1
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/projector_1
    behaviours:
      furniture:
        solid: false
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  office_furniture_v2_projector_2:
    display_name: Projector 2
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/projector_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_rubbishbin:
    display_name: Rubbishbin
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/rubbishbin
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_sofa_1:
    display_name: Sofa 1
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/sofa_1
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.9
        opposite_direction: true
        sit_all_solid_blocks: true
  office_furniture_v2_sofa_2:
    display_name: Sofa 2
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/sofa_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: -1
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.9
        opposite_direction: true
        sit_all_solid_blocks: true
  office_furniture_v2_tableceo:
    display_name: Tableceo
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/tableceo
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: -1
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_table_1:
    display_name: Table 1
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/table_1
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  office_furniture_v2_table_2:
    display_name: Table 2
    resource:
      material: paper
      generate: false
      model_path: office_furniture_v2/table_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: -1
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true