info:
  namespace: omc_blocks
items:
  grave:
    enabled: true
    display_name: grave
    resource:
      generate: false
      model_path: grave
      material: PAPER
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
        cancel_drop: true  