info:
  namespace: omc_blocks
categories:
  omc_blocks:
    enabled: true
    skip_if_already: false
    icon: omc_blocks:grave
    name: "OpenMC Blocks"
    permission: ia.menu.seecategory.omc_blocks
    items:
      - omc_blocks:grave