info:
  namespace: omc_blocks
items:
  banc:
    display_name: "Banc"
    resource:
      material: PAPER
      generate: false
      model_path: furnitures/banc
    behaviours:
      furniture_sit:
        sit_height: 0.8
      furniture:
        small: false
        solid: true
        fixed_rotation: true
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: -0.0
          height_offset: 0
        entity: item_display
        display_transformation:
          adjust_legacy_model: armor_stand
  cubedecompagnie:
    display_name: "Cube de compagnie"
    resource:
      generate: false
      material: PAPER
      model_path: furnitures/cubedecompagnie
    behaviours:
      furniture:
        entity: item_display
        display_transformation:
          adjust_legacy_model: armor_stand
  tablebois:
    display_name: "Table en bois"
    resource:
      generate: false
      material: PAPER
      model_path: furnitures/tablebois
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
        cancel_drop: true
        sound:
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.8
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.8    
  tablepierre:
    display_name: "Table en pierre"
    resource:
      generate: false
      material: PAPER
      model_path: furnitures/tablepierre
    specific_properties:
      block:
        placed_model:
          type: REAL_TRANSPARENT
        cancel_drop: true
        sound:
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.8
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.8      