info:
  namespace: omc_blocks
recipes:
  crafting_table:
    tablebois:
      enabled: true
      pattern:
      - DDD
      - BXB
      - BXB
      ingredients:
        B: STICK
        D: OAK_SLAB
      result:
        item: omc_blocks:tablebois
        amount: 1
    tablepierre:
      enabled: true
      pattern:
      - DDD
      - BXB
      - BXB
      ingredients:
        B: STONE
        D: STONE_SLAB
      result:
        item: omc_blocks:tablepierre
        amount: 1
    cubedecompagnie:
      enabled: true
      pattern:
      - FSF
      - SPS
      - FSF
      ingredients:
        S: STONE
        F: IRON_INGOT
        P: PINK_DYE
      result:
        item: omc_blocks:cubedecompagnie
        amount: 1
    caisse:
      enabled: true
      pattern:
      - BBB
      - BSB
      - BBB
      ingredients:
        S: STICK
        B: SPRUCE_PLANKS
      result:
        item: omc_blocks:caisse
        amount: 1
    cailloux:
      enabled: true
      pattern:
      - XXX
      - XXX
      - SSS
      ingredients:
        S: STONE_BUTTON
      result:
        item: omc_blocks:cailloux
        amount: 1