info:
  namespace: quests
items:
  quests_icon_left_arrow:
    enabled: true
    display_name: Pourquoi faire ?
    resource:
      material: PAPER
      generate: true
      textures:
        - items/arrow_left
  quests_icon_right_arrow:
    enabled: true
    display_name: Pourquoi faire ?
    resource:
      material: PAPER
      generate: true
      textures:
        - items/arrow_right
  quests_icon_left_arrow_disabled:
    enabled: true
    display_name: Pourquoi faire ?
    resource:
      material: PAPER
      generate: true
      textures:
        - items/arrow_left_disabled
  quests_icon_right_arrow_disabled:
    enabled: true
    display_name: Pourquoi faire ?
    resource:
      material: PAPER
      generate: true
      textures:
        - items/arrow_right_disabled