info:
  namespace: studio_pack
categories:
  studio_pack:
    enabled: true
    skip_if_already: false
    icon: "studio_pack:carpet_1"
    name: Studio Pack
    permission: ia.menu.studio_pack
    items:
      - "studio_pack:carpet_1"
      - "studio_pack:carpet_2"
      - "studio_pack:chair_1"
      - "studio_pack:chair_2"
      - "studio_pack:chair_3"
      - "studio_pack:guitar"
      - "studio_pack:laptop"
      - "studio_pack:microphone"
      - "studio_pack:mixer_1"
      - "studio_pack:mixer_2"
      - "studio_pack:mixer_3"
      - "studio_pack:monitor"
      - "studio_pack:mouse_keyboard"
      - "studio_pack:piano"
      - "studio_pack:shelf"
      - "studio_pack:sofa"
      - "studio_pack:speaker_1"
      - "studio_pack:speaker_2"
      - "studio_pack:speaker_3"
      - "studio_pack:speaker_4"
      - "studio_pack:stan"
      - "studio_pack:table"
      - "studio_pack:wall_1"
      - "studio_pack:wall_2"
