info:
  namespace: studio_pack
items:
  carpet_1:
    display_name: carpet_1
    resource:
      material: PAPER
      generate: false
      model_path: carpet_1
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_CARPET_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_CARPET_BREAK
            volume: 1
            pitch: 0.9
  carpet_2:
    display_name: carpet_2
    resource:
      material: PAPER
      generate: false
      model_path: carpet_2
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_CARPET_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_CARPET_BREAK
            volume: 1
            pitch: 0.9
  chair_1:
    display_name: chair_1
    resource:
      material: PAPER
      generate: false
      model_path: chair_1
    behaviours:
      furniture_sit:
        sit_height: 0.5
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOODEN_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOODEN_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  chair_2:
    display_name: chair_2
    resource:
      material: PAPER
      generate: false
      model_path: chair_2
    behaviours:
      furniture_sit:
        sit_height: 0.5
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOODEN_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOODEN_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  chair_3:
    display_name: chair_3
    resource:
      material: PAPER
      generate: false
      model_path: chair_3
    behaviours:
      furniture_sit:
        sit_height: 0.5
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOODEN_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOODEN_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  guitar:
    display_name: guitar
    resource:
      material: PAPER
      generate: false
      model_path: guitar
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  laptop:
    display_name: laptop
    resource:
      material: PAPER
      generate: false
      model_path: laptop
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  microphone:
    display_name: microphone
    resource:
      material: PAPER
      generate: false
      model_path: microphone
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 2
  mixer_1:
    display_name: mixer_1
    resource:
      material: PAPER
      generate: false
      model_path: mixer_1
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  mixer_2:
    display_name: mixer_2
    resource:
      material: PAPER
      generate: false
      model_path: mixer_2
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.9
  mixer_3:
    display_name: mixer_3
    resource:
      material: PAPER
      generate: false
      model_path: mixer_3
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.9
  monitor:
    display_name: monitor
    resource:
      material: PAPER
      generate: false
      model_path: monitor
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  mouse_keyboard:
    display_name: mouse_keyboard
    resource:
      material: PAPER
      generate: false
      model_path: mouse_keyboard
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
  piano:
    display_name: piano
    resource:
      material: PAPER
      generate: false
      model_path: piano
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOODEN_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOODEN_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 2
          height: 1
  shelf:
    display_name: shelf
    resource:
      material: PAPER
      generate: false
      model_path: shelf
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: false
          ceiling: false
          walls: true
        sound:
          place:
            name: BLOCK_WOODEN_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOODEN_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 2
          width: 1
          height: 1
  sofa:
    display_name: sofa
    resource:
      material: PAPER
      generate: false
      model_path: sofa
    behaviours:
      furniture_sit:
        sit_height: 0.5
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: -2
          height: 1
  speaker_1:
    display_name: speaker_1
    resource:
      material: PAPER
      generate: false
      model_path: speaker_1
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  speaker_2:
    display_name: speaker_2
    resource:
      material: PAPER
      generate: false
      model_path: speaker_2
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  speaker_3:
    display_name: speaker_3
    resource:
      material: PAPER
      generate: false
      model_path: speaker_3
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  speaker_4:
    display_name: speaker_4
    resource:
      material: PAPER
      generate: false
      model_path: speaker_4
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_METAL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_METAL_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  stan:
    display_name: stan
    resource:
      material: PAPER
      generate: false
      model_path: stan
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  table:
    display_name: table
    resource:
      material: PAPER
      generate: false
      model_path: table
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  wall_1:
    display_name: wall_1
    resource:
      material: PAPER
      generate: false
      model_path: wall_1
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        sound:
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  wall_2:
    display_name: wall_2
    resource:
      material: PAPER
      generate: false
      model_path: wall_2
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        sound:
          place:
            name: BLOCK_STONE_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_STONE_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
