info:
  namespace: aywen
items:
  home_bag:
    display_name: Sac de maison
    resource:
      material: CARROT_ON_A_STICK
      generate: true
      textures:
      - items/home_bag.png
    lore:
      - ''
      - '§6§lClick-droit§r§7 pour rentrer'
    events_settings:
      cooldown:
        indicator: HUD
        ticks: 300
recipes:
  crafting_table:
    home_bag:
      enabled: true
      pattern:
      - LRL
      - LCL
      - LLL
      ingredients:
        C: CHEST
        L: LEATHER
        R: RABBIT_HIDE
      result:
        item: aywen:home_bag
        amount: 1