info:
  namespace: merchant_pack
items:
  apple_basket_stand:
    display_name: apple_basket_stand
    resource:
      material: PAPER
      generate: false
      model_path: apple_basket_stand
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
  basket_with_health_potions:
    display_name: basket_with_health_potions
    resource:
      material: PAPER
      generate: false
      model_path: basket_with_health_potions
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1

  basket_with_mana_potions:
    display_name: basket_with_mana_potions
    resource:
      material: PAPER
      generate: false
      model_path: basket_with_mana_potions
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1

  blue_book:
    display_name: Blue book
    resource:
      material: POTION
      generate: false
      model_path: blue_book
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOL_BREAK
            volume: 1
            pitch: 0.9


  blue_merchant_booth:
    display_name: blue_merchant_booth
    resource:
      material: PAPER
      generate: false
      model_path: blue_merchant_booth
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 3
          height: 2
          length_offset: 0
          width_offset: 1
          height_offset: 0 

  carrot:
    display_name: carrot
    resource:
      material: PAPER
      generate: false
      model_path: carrot
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_GRASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GRASS_BREAK
            volume: 1
            pitch: 0.9

  carrot_basket_stand:
    display_name: carrot_basket_stand
    resource:
      material: PAPER
      generate: false
      model_path: carrot_basket_stand
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_GRASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GRASS_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0 

  empty_basket_stand:
    display_name: empty_basket_stand
    resource:
      material: PAPER
      generate: false
      model_path: empty_basket_stand
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0 

  empty_basket:
    display_name: empty_basket
    resource:
      material: PAPER
      generate: false
      model_path: empty_basket
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0

  health_potion:
    display_name: health_potion
    resource:
      material: PAPER
      generate: false
      model_path: health_potion
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_GLASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GLASS_BREAK
            volume: 1
            pitch: 0.9

  mana_potion:
    display_name: mana_potion
    resource:
      material: PAPER
      generate: false
      model_path: mana_potion
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_GLASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GLASS_BREAK
            volume: 1
            pitch: 0.9

  potato_basket_stand:
    display_name: potato_basket_stand
    resource:
      material: PAPER
      generate: false
      model_path: potato_basket_stand
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 1
          height: 1

  props_blue_merchant_booth:
    display_name: props_blue_merchant_booth
    resource:
      material: PAPER
      generate: false
      model_path: props_blue_merchant_booth
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: 1
          height_offset: 0

  red_merchant_booth:
    display_name: red_merchant_booth
    resource:
      material: PAPER
      generate: false
      model_path: red_merchant_booth
    behaviours:
      furniture:
        entity: item_frame
        solid: true
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOD_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOD_BREAK
            volume: 1
            pitch: 0.9
        hitbox:
          length: 1
          width: 3
          height: 1
          length_offset: 0
          width_offset: 1
          height_offset: 0

  red_book:
    display_name: red_book
    resource:
      material: PAPER
      generate: false
      model_path: red_book
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOL_BREAK
            volume: 1
            pitch: 0.9

  scrolls:
    display_name: scrolls
    resource:
      material: PAPER
      generate: false
      model_path: scrolls
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOL_BREAK
            volume: 1
            pitch: 0.9

  stack_blue_book:
    display_name: stack_blue_book
    resource:
      material: PAPER
      generate: false
      model_path: stack_blue_book
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOL_BREAK
            volume: 1
            pitch: 0.9

  stack_red_book:
    display_name: stack_red_book
    resource:
      material: PAPER
      generate: false
      model_path: stack_red_book
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_WOOL_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_WOOL_BREAK
            volume: 1
            pitch: 0.9

  stack_of_bottles:
    display_name: stack_of_bottles
    resource:
      material: PAPER
      generate: false
      model_path: stack_of_bottles
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_GLASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GLASS_BREAK
            volume: 1
            pitch: 0.9

  stack_of_potions:
    display_name: stack_of_potions
    resource:
      material: PAPER
      generate: false
      model_path: stack_of_potions
    behaviours:
      furniture:
        entity: item_frame
        solid: false
        small: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: BLOCK_GLASS_PLACE
            volume: 1
            pitch: 0.9
          break:
            name: BLOCK_GLASS_BREAK
            volume: 1
            pitch: 0.9