info:
  namespace: elitecreatures
categories:
  nightclub_furniture_v1:
    enabled: true
    icon: elitecreatures:nightclub_ball_discotect
    name: Nightclub Furniture v1
    permission: permission.nightclub_furniture_v1
    items:
    - elitecreatures:nightclub_ball_discotect
    - elitecreatures:nightclub_chair
    - elitecreatures:nightclub_chair_2
    - elitecreatures:nightclub_chair_3
    - elitecreatures:nightclub_fridge_1
    - elitecreatures:nightclub_fridge_2
    - elitecreatures:nightclub_light
    - elitecreatures:nightclub_mixer
    - elitecreatures:nightclub_pole
    - elitecreatures:nightclub_shelf_1
    - elitecreatures:nightclub_shelf_2
    - elitecreatures:nightclub_sign
    - elitecreatures:nightclub_sofa_double
    - elitecreatures:nightclub_speaker
    - elitecreatures:nightclub_tower_beer

items:
  nightclub_ball_discotect:
    display_name: nightclub ball discotect
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_ball_discotect
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_chair:
    display_name: nightclub chair
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_chair
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_chair_2:
    display_name: nightclub chair 2
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_chair_2
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_chair_3:
    display_name: nightclub chair 3
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_chair_3
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_fridge_1:
    display_name: nightclub fridge 1
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_fridge_1
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_fridge_2:
    display_name: nightclub fridge 2
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_fridge_2
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_light:
    display_name: nightclub light
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_light
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_mixer:
    display_name: nightclub mixer
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_mixer
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_pole:
    display_name: nightclub pole
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_pole
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_shelf_1:
    display_name: nightclub shelf 1
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_shelf_1
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_shelf_2:
    display_name: nightclub shelf 2
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_shelf_2
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_sign:
    display_name: nightclub sign
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_sign
    behaviours:
      furniture:
        entity: item_frame
  nightclub_sofa_double:
    display_name: nightclub sofa double
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_sofa_double
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_speaker:
    display_name: nightclub speaker
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_speaker
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  nightclub_tower_beer:
    display_name: nightclub tower beer
    resource:
      material: PAPER
      generate: false
      model_path: nightclub_furniture_v1/nightclub_tower_beer
    behaviours:
      furniture:
        fixed_rotation: false
        small: false
        solid: true
        hitbox:
          length: 1
          width: 1
          height: 1
        placeable_on:
          floor: true
          ceiling: false
          walls: false
  
  

# 40552J7