info:
  namespace: elitecreatures
categories:
  medieval_tavern_furniture_v1:
    enabled: true
    icon: "elitecreatures:medieval_tavern_furniture_v1_chair"
    name: "Medieval Tavern Furniture v1"
    permission: "ia.menu.medieval_tavern_furniture_v1"
    items:
      - "elitecreatures:medieval_tavern_furniture_v1_bar"
      - "elitecreatures:medieval_tavern_furniture_v1_bar_chair"
      - "elitecreatures:medieval_tavern_furniture_v1_bar_corner"
      - "elitecreatures:medieval_tavern_furniture_v1_bar_sign"
      - "elitecreatures:medieval_tavern_furniture_v1_barrel_stack"
      - "elitecreatures:medieval_tavern_furniture_v1_beer_tank"
      - "elitecreatures:medieval_tavern_furniture_v1_beer_tank_wall"
      - "elitecreatures:medieval_tavern_furniture_v1_candle"
      - "elitecreatures:medieval_tavern_furniture_v1_carpet"
      - "elitecreatures:medieval_tavern_furniture_v1_chair"
      - "elitecreatures:medieval_tavern_furniture_v1_dart_board"
      - "elitecreatures:medieval_tavern_furniture_v1_drinking_horn"
      - "elitecreatures:medieval_tavern_furniture_v1_glass_hanging_bar"
      - "elitecreatures:medieval_tavern_furniture_v1_shelf_1"
      - "elitecreatures:medieval_tavern_furniture_v1_shelf_2"
      - "elitecreatures:medieval_tavern_furniture_v1_shelf_3"
      - "elitecreatures:medieval_tavern_furniture_v1_shelf_4"
      - "elitecreatures:medieval_tavern_furniture_v1_table"
      - "elitecreatures:medieval_tavern_furniture_v1_wall_lamp"
      - "elitecreatures:medieval_tavern_furniture_v1_wantd_paper"
