info:
  namespace: elitecreatures
items:
  medieval_tavern_furniture_v1_bar:
    display_name: Bar
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/bar
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_bar_chair:
    display_name: Bar Chair
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/bar_chair
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 1.1
        opposite_direction: true
        sit_all_solid_blocks: true
  medieval_tavern_furniture_v1_bar_corner:
    display_name: Bar Corner
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/bar_corner
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_bar_sign:
    display_name: Bar Sign
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/bar_sign
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  medieval_tavern_furniture_v1_barrel_stack:
    display_name: Barrel Stack
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/barrel_stack
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 3
          height: 3
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_beer_tank:
    display_name: Beer Tank
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/beer_tank
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_beer_tank_wall:
    display_name: Beer Tank Wall
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/beer_tank_wall
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  medieval_tavern_furniture_v1_candle:
    display_name: Candle
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/candle
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        light_level: 10
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_carpet:
    display_name: Carpet
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/carpet
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 2
          width: 2
          height: 1
          length_offset: -0.5
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_chair:
    display_name: Chair
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/chair
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
      furniture_sit:
        sit_height: 0.95
        opposite_direction: true
        sit_all_solid_blocks: true
  medieval_tavern_furniture_v1_dart_board:
    display_name: Dart Board
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/dart_board
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  medieval_tavern_furniture_v1_drinking_horn:
    display_name: Drinking Horn
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/drinking_horn
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_glass_hanging_bar:
    display_name: Glass Hanging Bar
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/glass_hanging_bar
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: item_frame
        hitbox:
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: true
          floor: false
  medieval_tavern_furniture_v1_shelf_1:
    display_name: Shelf 1
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/shelf_1
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 2
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_shelf_2:
    display_name: Shelf 2
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/shelf_2
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 3
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_shelf_3:
    display_name: Shelf 3
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/shelf_3
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 2
          height: 2
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_shelf_4:
    display_name: Shelf 4
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/shelf_4
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 2
          height: 1
          length_offset: 0
          width_offset: -0.5
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  medieval_tavern_furniture_v1_table:
    display_name: Table
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/table
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: false
          ceiling: false
          floor: true
  medieval_tavern_furniture_v1_wall_lamp:
    display_name: Wall Lamp
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/wall_lamp
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        light_level: 10
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false
  medieval_tavern_furniture_v1_wantd_paper:
    display_name: Wantd Paper
    resource:
      material: PAPER
      generate: false
      model_path: medieval_tavern_furniture_v1/wantd_paper
    behaviours:
      furniture:
        solid: true
        fixed_rotation: true
        entity: armor_stand
        hitbox:
          length: 1
          width: 1
          height: 1
          length_offset: 0
          width_offset: 0
          height_offset: 0
        placeable_on:
          walls: true
          ceiling: false
          floor: false


# 03232HFRMQCIO