info:
  namespace: kitchen
categories:
  kitchen:
    enabled: true
    icon: kitchen:kitchen_cookerhood
    name: "&6Kitchen"
    items:
      - kitchen:kitchen_barstool
      - kitchen:kitchen_bin
      - kitchen:kitchen_chair
      - kitchen:kitchen_cookerhood
      - kitchen:kitchen_dish
      - kitchen:kitchen_dish_pile
      - kitchen:kitchen_element
      - kitchen:kitchen_fridge
      - kitchen:kitchen_knifes
      - kitchen:kitchen_microwave
      - kitchen:kitchen_pan
      - kitchen:kitchen_pot
      - kitchen:kitchen_sink
      - kitchen:kitchen_stove
      - kitchen:kitchen_wall_element
      - kitchen:kitchen_wine
      - kitchen:kitchen_winerack