info:
  namespace: kitchen
items:
  kitchen_barstool:
    display_name: "Kitchen Barstool"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_barstool
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
      furniture_sit:
        sit_height: 1.2
  kitchen_bin:
    display_name: "Kitchen Bin"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_bin
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_chair:
    display_name: "Kitchen Chair"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_chair
    behaviours:
      furniture:
        gravity: false
        light_level: 10
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
      furniture_sit:
        sit_height: 0.9
  kitchen_cookerhood:
    display_name: "Kitchen Cookerhood"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_cookerhood
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: false
        placeable_on:
          floor: false
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_dish:
    display_name: "Dish"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_dish
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_dish_pile:
    display_name: "Dish Pile"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_dish_pile
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_element:
    display_name: "Kitchen Base Element"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_element
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_fridge:
    display_name: "Kitchen Fridge"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_fridge
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 2
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_knifes:
    display_name: "Kitchen Knifes"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_knifes
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small_hitbox: false
        solid: false
        placeable_on:
          floor: false
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_microwave:
    display_name: "Kitchen Microwave"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_microwave
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small_hitbox: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_pan:
    display_name: "Pan"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_pan
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_pot:
    display_name: "Pot"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_pot
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_sink:
    display_name: "Kitchen Sink"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_sink
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_stove:
    display_name: "Kitchen Stove"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_stove
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_wall_element:
    display_name: "Kitchen Wall Element"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_wall_element
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small: false
        solid: true
        placeable_on:
          floor: false
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_wine:
    display_name: "Wine"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_wine
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small_hitbox: false
        solid: false
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break
  kitchen_winerack:
    display_name: "Kitchen Winerack"
    permission: "kitchen"
    resource:
      generate: false
      material: PAPER
      model_path: furniture/kitchen/kitchen_winerack
    behaviours:
      furniture:
        gravity: false
        fixed_rotation: true
        small_hitbox: false
        solid: false
        placeable_on:
          floor: true
          ceiling: false
          walls: true
        hitbox:
          length: 1
          width: 1
          height: 1
        sound:
          place:
            name: block.wooden.place
          break:
            name: block.wooden.break

# 4192N38I91NC5TTEL8VABDK