info:
  namespace: aywen
items:
  dream_log:
    display_name: Dream Log
    resource:
      generate: true
      material: PAPER
      textures:
        - blocks/dreamlog_top.png
        - blocks/dreamlog.png
        - blocks/dreamlog.png
        - blocks/dreamlog.png
        - blocks/dreamlog_top.png
        - blocks/dreamlog.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
          break_sound: BLOCK_WOOD_BREAK
          place_sound: BLOCK_WOOD_PLACE
          step_sound: BLOCK_WOOD_STEP
          hardness: 2
          resistance: 2
          light_level: 1
          tool: AXE
          flammable: true
          catch_fire: true

  stripped_dream_log:
    display_name: Stripped Dream Log
    resource:
      generate: true
      material: PAPER
      textures:
        - blocks/stripped_dreamlog_top.png
        - blocks/stripped_dreamlog.png
        - blocks/stripped_dreamlog.png
        - blocks/stripped_dreamlog.png
        - blocks/stripped_dreamlog_top.png
        - blocks/stripped_dreamlog.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
          break_sound: BLOCK_WOOD_BREAK
          place_sound: BLOCK_WOOD_PLACE
          step_sound: BLOCK_WOOD_STEP
          hardness: 2
          resistance: 2
          light_level: 1
          tool: AXE
          flammable: true
          catch_fire: true

  dream_planks:
    display_name: Dream Planks
    resource:
      generate: true
      material: PAPER
      textures:
        - blocks/dreamplank.png
    specific_properties:
      block:
        break_tools_whitelist:
        - _AXE
        - _axe
        - HAND
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
          break_sound: BLOCK_WOOD_BREAK
          place_sound: BLOCK_WOOD_PLACE
          step_sound: BLOCK_WOOD_STEP
          hardness: 2
          resistance: 3
          light_level: 0
          flammable: true
          catch_fire: true

  cloud:
    display_name: Nuage
    resource:
      generate: true
      material: PAPER
      model_id: 44001
      textures:
        - blocks/cloud.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
          break_sound: BLOCK_WOOL_BREAK
          place_sound: BLOCK_WOOL_PLACE
          step_sound: BLOCK_WOOL_STEP
          hardness: 0.2
          resistance: 0.2
          light_level: 0
          flammable: false
          catch_fire: false

recipes:
  crafting_table:
    dream_planks:
      enabled: true
      shapeless: true
      ingredients:
        A: aywen:dream_log
      result:
        item: aywen:dream_planks
        amount: 4
    ct:
      enabled: true
      pattern:
      - WW
      - WW
      ingredients:
        W: aywen:dream_planks
      result:
        item: CRAFTING_TABLE
        amount: 1
    bed:
      enabled: true
      pattern:
      - XXX
      - CCC
      - WWW
      ingredients:
        C: aywen:cloud
        W: aywen:dream_planks
      result:
        item: WHITE_BED
        amount: 1