info:
  namespace: aywen

items:
  moon_fish:
    display_name: Poisson-lune
    resource:
      material: SALMON
      generate: true
      model_id: 44008
      textures:
        - items/moon_fish.png
    events:
      eat:
        feed:
          amount: 2
          saturation: 0.4
  sun_fish:
    display_name: Poisson-soleil
    resource:
      material: COOKED_SALMON
      generate: true
      model_id: 44007
      textures:
        - items/sun_fish.png
    lore:
      - '§7Attention! Vous risquez'
      - '§7de vous brulez!'
    events:
      eat:
        feed:
          amount: 6
          saturation: 9.6

  poissonion:
    display_name: Poissonion
    resource:
      material: COD
      generate: true
      model_id: 44008
      textures:
        - items/poissonion.png
    lore:
      - '§7On dirait un onion...'
    events:
      eat:
        feed:
          amount: 2
          saturation: 0.4
  cooked_poissonion:
    display_name: Poissonion cuit
    resource:
      material: COOKED_COD
      model_id: 44010
      generate: true
      textures:
        - items/cooked_poissonion.png
    lore:
      - '§7Mot du dev:'
      - '§7Il est plus beau cru'
    events:
      eat:
        feed:
          amount: 5
          saturation: 6

  dockerfish:
    display_name: Poisson Docker
    resource:
      material: COD
      generate: true
      model_id: 44006
      textures:
        - items/dockerfish.png
    events:
      eat:
        feed:
          amount: 2
          saturation: 0.4

recipes:
  cooking:
    sun_fish:
      ingredient:
        item: aywen:moon_fish
      exp: 1
      machines:
        - FURNACE
        - SMOKER
      result:
        item: aywen:sun_fish
        amount: 1
    poissonion:
      ingredient:
        item: aywen:poissonion
      exp: 1
      machines:
        - FURNACE
        - SMOKER
      result:
        item: aywen:cooked_poissonion
        amount: 1
  crafting_table:
    kebab_fish:
      enabled: true
      shapeless: true
      ingredients:
        A: aywen:salade
        B: aywen:tomate
        C: aywen:cooked_poissonion
        D: BREAD
      result:
        item: aywen:kebab
        amount: 1