info:
  namespace: aywen
items:
  somnifere:
    display_name: Somnifère
    resource:
      material: DRIED_KELP
      generate: true
      textures:
      - items/somnifere.png
    lore:
      - '§7Vous allez faire un gros dodo'
  dream_essence:
    display_name: Essence de rêve
    resource:
      material: PAPER
      generate: true
      model_id: 44004
      textures:
      - items/dream_essence.png
  totem_of_undreaming:
    display_name: §eTotem de réveil§r
    resource:
      material: PAPER
      model_id: 44003
      generate: true
      textures:
        - items/totem.png
  cloud_soup:
    display_name: Soupe de nuage
    lore:
      - '§7Vous permets de volez'
      - '§7pendant 5 minutes (cumulable)'
    resource:
      material: BEETROOT_SOUP
      generate: true
      model_id: 44005
      textures:
        - items/cloud_soup.png
  microphone:
    display_name: Microphone
    resource:
      material: PAPER
      generate: true
      textures:
        - items/micro.png
    events:
      interact:
        right:
          execute_commands:
            cmd1:
              command: 'proxichat mutetoggle'
  codex_somnii:
    display_name: Codex Somnii
    lore:
    - '§7Receuil de la dimension'
    - '§7du rêve'
    resource:
      material: PAPER
      generate: true
      model_id: 44002
      textures:
        - items/codex_somnii.png

recipes:
  crafting_table:
    somnifere:
      enabled: true
      pattern:
        - SRS
        - SRS
        - SRS
      ingredients:
        S: SUGAR
        R: aywen:dream_essence
      result:
        item: aywen:somnifere
        amount: 1
    totem_of_undreaming:
      enabled: true
      pattern:
      - CCC
      - CRC
      - XSX
      ingredients:
        C: CRYING_OBSIDIAN
        R: aywen:dream_essence
        S: aywen:somnifere
      result:
        item: aywen:totem_of_undreaming
        amount: 1
    cloud_soup:
      enabled: true
      pattern:
      - CCC
      - CWC
      - XBX
      ingredients:
        W: WIND_CHARGE
        C: aywen:cloud
        B: BOWL
      result:
        item: aywen:cloud_soup
        amount: 1
    codex_somnii:
      enabled: true
      shapeless: true
      ingredients:
        B: BOOK
        E: aywen:dream_essence
      result:
        item: aywen:codex_somnii
        amount: 1