info:
  namespace: thor
items:
  hammer:
    enabled: true
    display_name: '&r&6Thor''s Hammer'
    lore:
    - '&rL''arme mythique du dieu de la foudre.'
    - ''
    - '&7&o(Shift + Clique droit) Invoquer la foudre'
    resource:
      material: GOLDEN_AXE
      generate: false
      model_path: hammer
    durability:
      max_custom_durability: 50
    blocked_enchants:
    - EFFICIENCY
    attribute_modifiers:
      mainhand:
        attackDamage: 10
        attackSpeed: 0.5
recipes:
  crafting_table:
    thorhammer:
      enabled: false
      pattern:
      - CCC
      - CGC
      - XSX
      ingredients:
        G: GOLD_BLOCK
        C: COBBLESTONE
        S: STICK
      result:
        item: thor:hammer
        amount: 1
